# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/s74r366/Documents/GitHub/star-3gg/UnrealEngineStudioModifications
GAMEPROJECTFILE =/home/s74r366/Documents/Unreal Projects/CityOfLight/CityOfLight.uproject

TARGETS = \
	UnrealClient-Linux-Debug  \
	UnrealClient-Linux-DebugGame  \
	UnrealClient-Linux-Test  \
	UnrealClient-Linux-Shipping  \
	UnrealClient \
	UnrealEditor-Linux-Debug  \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Test  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-Debug  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Test  \
	UnrealGame-Linux-Shipping  \
	UnrealGame \
	UnrealServer-Linux-Debug  \
	UnrealServer-Linux-DebugGame  \
	UnrealServer-Linux-Test  \
	UnrealServer-Linux-Shipping  \
	UnrealServer \
	CityOfLight-Linux-Debug  \
	CityOfLight-Linux-DebugGame  \
	CityOfLight-Linux-Test  \
	CityOfLight-Linux-Shipping  \
	CityOfLight \
	CityOfLightEditor-Linux-Debug  \
	CityOfLightEditor-Linux-DebugGame  \
	CityOfLightEditor-Linux-Test  \
	CityOfLightEditor-Linux-Shipping  \
	CityOfLightEditor\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = "$(UNREALROOTPATH)/Engine/Binaries/ThirdParty/DotNet/6.0.302/linux/dotnet" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend CityOfLightEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug CityOfLightEditor-Linux-Debug


UnrealClient-Linux-Debug:
	 $(BUILD) UnrealClient Linux Debug  $(ARGS)

UnrealClient-Linux-DebugGame:
	 $(BUILD) UnrealClient Linux DebugGame  $(ARGS)

UnrealClient-Linux-Test:
	 $(BUILD) UnrealClient Linux Test  $(ARGS)

UnrealClient-Linux-Shipping:
	 $(BUILD) UnrealClient Linux Shipping  $(ARGS)

UnrealClient:
	 $(BUILD) UnrealClient Linux Development  $(ARGS)

UnrealEditor-Linux-Debug:
	 $(BUILD) UnrealEditor Linux Debug  $(ARGS)

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Test:
	 $(BUILD) UnrealEditor Linux Test  $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealGame-Linux-Debug:
	 $(BUILD) UnrealGame Linux Debug  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Test:
	 $(BUILD) UnrealGame Linux Test  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealServer-Linux-Debug:
	 $(BUILD) UnrealServer Linux Debug  $(ARGS)

UnrealServer-Linux-DebugGame:
	 $(BUILD) UnrealServer Linux DebugGame  $(ARGS)

UnrealServer-Linux-Test:
	 $(BUILD) UnrealServer Linux Test  $(ARGS)

UnrealServer-Linux-Shipping:
	 $(BUILD) UnrealServer Linux Shipping  $(ARGS)

UnrealServer:
	 $(BUILD) UnrealServer Linux Development  $(ARGS)

CityOfLight-Linux-Debug:
	 $(PROJECTBUILD) CityOfLight Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

CityOfLight-Linux-DebugGame:
	 $(PROJECTBUILD) CityOfLight Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

CityOfLight-Linux-Test:
	 $(PROJECTBUILD) CityOfLight Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

CityOfLight-Linux-Shipping:
	 $(PROJECTBUILD) CityOfLight Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

CityOfLight:
	 $(PROJECTBUILD) CityOfLight Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

CityOfLightEditor-Linux-Debug:
	 $(PROJECTBUILD) CityOfLightEditor Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

CityOfLightEditor-Linux-DebugGame:
	 $(PROJECTBUILD) CityOfLightEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

CityOfLightEditor-Linux-Test:
	 $(PROJECTBUILD) CityOfLightEditor Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

CityOfLightEditor-Linux-Shipping:
	 $(PROJECTBUILD) CityOfLightEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

CityOfLightEditor:
	 $(PROJECTBUILD) CityOfLightEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
